modLoader="javafml"
loaderVersion="[28,)" # Forge version
issueTrackerURL="https://github.com/svenhjol/Charmonium/issues"
displayURL="https://svenhjol.github.io/Charm/"
#logoFile="examplemod.png"
#credits="Credits"

[[mods]]
modId="charmonium"
version="${version}" #mandatory
displayName="Charmonium"
description='''
Ambient sounds and additional music for Charm.
'''
authors="svenhjol"

[[dependencies.charmonium]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28.2,)" #mandatory
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER

[[dependencies.charmonium]]
    modId="charm" #mandatory
    mandatory=true #mandatory
    versionRange="[1.14.4-1.5.5,)" #mandatory
    ordering="AFTER" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER